name: fitmodeco_navbar
description: App de The FitMode.

version: 1.1.9+17

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  firebase_messaging:
  decimal: ^0.3.5
  url_launcher: ^5.4.1
  curved_navigation_bar: ^0.3.1 #latest version
  # dependencias de recepies firebase
  image_picker: ^0.6.3+1
  cloud_firestore: ^0.13.0
  font_awesome_flutter: ^8.5.0
  firebase_auth: ^0.15.4
  firebase_storage: ^3.1.1
  date_format: ^1.0.8
  intl: ^0.16.1
  modal_progress_hud: ^0.1.3
  intro_slider: ^2.2.8
  path_provider: ^1.6.0
  # Spoonacular
  http: ^0.12.0+4
  webview_flutter: ^0.3.19

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/rutinas/
  #  - images/a_dot_ham.jpeg
